# Generated by Django 3.1.5 on 2021-01-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, unique=True)),
                ('one_choice', models.CharField(max_length=30)),
                ('two_choice', models.CharField(max_length=30)),
                ('three_choice', models.CharField(max_length=30)),
                ('one_choice_count', models.IntegerField(default=0)),
                ('two_choice_count', models.IntegerField(default=0)),
                ('three_choice_count', models.IntegerField(default=0)),
            ],
        ),
    ]
